### ISSUE TITLE
Path matching doesn't work with optional path params

### ISSUE THREAD

**Issue by naugtur** [atlassian/oas3-chow-chow#19]
https://github.com/atlassian/oas3-chow-chow/blob/a46b746013710c7aceb7cadf18e20a964ca0ceb8/src/compiler/CompiledPath.ts doesn't seem to implement matching paths with a missing field where the last field in the path is marked as optional. 

pet/{petId} will not match pet/ even if petId was defined as optional

**Comment by naugtur** [comment]
@supertong are you still maintaining or should I look for a contact at Atlassian?
I'd like to contribute fixes for path resolution but I need some guidance and reasons to believe my contributions would be released ;)

**Comment by supertong** [comment]
Hey @naugtur, sorry for the late response. Yes, I am still maintaining this library. The library has been used in some of our production services, however, I am only able to maintain it  during my spare time. I have raised the request to include the maintenance of this library into our sprint planning. Hopefully that I will have more time spent on this library soon.
Regarding your request, I think the path parameter should not be optional according to OpenAPI spec.

> Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

I think it makes sense because it would be very hard to tell the differences between
`/pet` and `/pet/{petId}` if `{petId}` is optional.

**Comment by naugtur** [comment]
oh, right... well, I ended up solving it like that in one place already. 
The docs look bad when I'm specifying an endpoint for filesystem listing and I want to serve root folder on `/` and then other folders in `/{id}`

Thanks for pointing this out.
